const mongoose = require('mongoose')
const { model, Schema, ObjectId } = mongoose
const ProductModel = require('./product')

module.exports = model('Order', new Schema({
  ownerId: ObjectId,
  side: {type: String, enum: ['buy', 'sell']},
  product: ProductModel.schema,
  quantity: Number,
  createdDate: Date,

  // per unit
  price: Number,

  // if it was autogenerated by the engine, if yes, then it can be autorefilled, otherwise
  // user's orders shoudl not be autorefilled
  public: Boolean,
}), 'order')
